import { RepoAnalysis, RepoFile, DatabaseSchema, RepoDependency, SecurityFinding } from '../types';

export interface SpecGeneratorOptions {
  includeOverview?: boolean;
  includeArchitecture?: boolean;
  includePrompts?: boolean;
  includeDatabase?: boolean;
  includeDependencies?: boolean;
  includeSecurity?: boolean;
}

export const MarkdownSpecGenerator = {
  generateSpec(
    analysis: RepoAnalysis,
    files: RepoFile[],
    fileContents: Map<string, string>,
    databaseSchema?: DatabaseSchema | null,
    dependencies?: RepoDependency[] | null,
    securityFindings?: SecurityFinding[],
    options: SpecGeneratorOptions = {
      includeOverview: true,
      includeArchitecture: true,
      includePrompts: true,
      includeDatabase: true,
      includeDependencies: true,
      includeSecurity: true,
    }
  ): string {
    const lines: string[] = [];

    const repoTitle = analysis.metadata.fullName || 'Repository';

    // Header
    lines.push(`# Reverse Engineering & System Architecture Specification`);
    lines.push(`> **Project**: ${repoTitle}`);
    lines.push(`> **Primary Language**: ${analysis.metadata.language}`);
    lines.push(`> **Generated By**: DomoScope AI Engine`);
    lines.push(`> **Timestamp**: ${new Date().toISOString()}`);
    lines.push(``);

    // 1. Executive Summary
    if (options.includeOverview) {
      lines.push(`## 1. Executive Summary & Overview`);
      lines.push(`${analysis.summary}`);
      lines.push(``);
      lines.push(`- **Total Inspectable Files**: ${files.length}`);
      lines.push(`- **Detected Frameworks & Tools**: ${analysis.detectedTools.join(', ') || 'Standard Runtime'}`);
      lines.push(`- **Entry Point File(s)**: ${analysis.entryPoints.map((e) => `\`${e}\``).join(', ') || 'None detected'}`);
      lines.push(``);
    }

    // 2. Architecture & File Breakdown
    if (options.includeArchitecture) {
      lines.push(`## 2. Component & Architecture Breakdown`);
      lines.push(`The codebase is organized into key structural layers:`);
      lines.push(``);

      const categories: Record<string, RepoFile[]> = {};
      files.forEach((f) => {
        const cat = f.category || 'other';
        if (!categories[cat]) categories[cat] = [];
        categories[cat].push(f);
      });

      for (const [catName, catFiles] of Object.entries(categories)) {
        lines.push(`### ${catName.toUpperCase()} Layer (${catFiles.length} files)`);
        catFiles.slice(0, 8).forEach((f) => {
          lines.push(`- \`${f.path}\` (${f.size || 0} bytes)`);
        });
        if (catFiles.length > 8) {
          lines.push(`- *...and ${catFiles.length - 8} more files*`);
        }
        lines.push(``);
      }
    }

    // 3. Database Schema & Data Models
    if (options.includeDatabase && databaseSchema && databaseSchema.tables.length > 0) {
      const typesStr = databaseSchema.detectedTypes.join(', ') || 'Relational Database';
      lines.push(`## 3. Database Schemas & Data Models`);
      lines.push(`Detected schema types: **${typesStr}** (${databaseSchema.tables.length} tables)`);
      lines.push(``);

      databaseSchema.tables.forEach((t) => {
        lines.push(`#### Table: \`${t.name}\``);
        lines.push(`| Column | Type | Primary Key | Nullable |`);
        lines.push(`| :--- | :--- | :--- | :--- |`);
        t.columns.forEach((c) => {
          lines.push(`| \`${c.name}\` | \`${c.type}\` | ${c.isPrimary ? 'Yes' : 'No'} | ${c.isNullable ? 'Yes' : 'No'} |`);
        });
        lines.push(``);
      });
    }

    // 4. Custom LLM Reverse-Engineering Prompts
    if (options.includePrompts) {
      lines.push(`## 4. LLM Reverse-Engineering System Prompts`);
      lines.push(`Copy and paste these pre-constructed system prompts into any AI model (GPT-4o, Claude, Gemini, WebLLM) to reverse-engineer or recreate specific subsystems of this repository.`);
      lines.push(``);

      // Prompt A: Full Architecture Recreation
      lines.push(`### Prompt A: Recreate Full Architecture`);
      lines.push(`\`\`\`markdown`);
      lines.push(`You are an expert software architect tasked with reverse-engineering the project "${repoTitle}".`);
      lines.push(`Primary Stack: ${analysis.metadata.language}, ${analysis.detectedTools.join(', ')}.`);
      lines.push(`Entry Points: ${analysis.entryPoints.join(', ')}.`);
      lines.push(``);
      lines.push(`Goal: Construct a step-by-step technical plan to rebuild this application from scratch.`);
      lines.push(`Provide:`);
      lines.push(`1. Folder structure and file scaffolding.`);
      lines.push(`2. Core API contracts and data flow diagrams.`);
      lines.push(`3. Component state management pattern.`);
      lines.push(`\`\`\``);
      lines.push(``);

      // Prompt B: File-Specific Reverse Engineering
      if (analysis.entryPoints.length > 0) {
        const primary = analysis.entryPoints[0];
        const excerpt = fileContents.get(primary)?.slice(0, 1000) || '';
        lines.push(`### Prompt B: Reverse Engineer Core Entry Point (\`${primary}\`)`);
        lines.push(`\`\`\`markdown`);
        lines.push(`Analyze the following entry point source code from "${repoTitle}" (\`${primary}\`):`);
        lines.push(``);
        lines.push(excerpt);
        lines.push(``);
        lines.push(`Tasks:`);
        lines.push(`1. Identify all imported dependencies and explain their purpose.`);
        lines.push(`2. Extract the initialization logic step-by-step.`);
        lines.push(`3. Highlight any potential performance bottlenecks or edge-case handling.`);
        lines.push(`\`\`\``);
        lines.push(``);
      }
    }

    // 5. Dependencies & Security Summary
    if (options.includeDependencies && dependencies) {
      lines.push(`## 5. Dependencies & Security Audit`);
      lines.push(`- **Total Dependencies**: ${dependencies.length}`);
      lines.push(`- **Vulnerabilities Found**: ${securityFindings?.length || 0}`);
      lines.push(``);

      if (securityFindings && securityFindings.length > 0) {
        lines.push(`### Security Findings`);
        securityFindings.forEach((f) => {
          lines.push(`- **[${f.severity.toUpperCase()}]** \`${f.file}\` (Line ${f.line}): ${f.title} - ${f.explanation}`);
        });
        lines.push(``);
      }
    }

    lines.push(`---`);
    lines.push(`*Generated by DomoScope — Open Source Repository Inspector*`);

    return lines.join('\n');
  },

  downloadMarkdownFile(filename: string, content: string): void {
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', filename);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  },
};
